name: Unit test
on: 
  push:
    branches: [main]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Installing dependencies
        run: npm install
      - name: Starting unit test
        run: npm run test
