name: Unit test
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print installing dependencies
        run: echo "Installing dependencies"
      - name: Install dependencies
        run: npm install
      - name: Print start unit test
        run: echo "Starting unit test"
      - name: Start unit test
        run: npm run test
      - name: Print unit test end
        run: echo "Unitest fished."
