name: Unit test
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Installing dependencies
        run: |
          cd rankingsRepoExcel/
          npm install
      - name: Starting unit test
        run: npm run test
